// Probabili titolari Serie A 2026/27 — fonte: Goal.com, probabili formazioni aggiornate al 9 agosto 2026
// (Formazioni_Titolari_SerieA_2026-27.md). Abbinato per nome+squadra come appaiono nel listone
// "Quotazioni Fantacalcio" ufficiale. Sono esclusi 2 nominativi della fonte senza corrispondenza
// chiara nel listone (probabili refusi dell'articolo originale): "Maldini" per il Cagliari,
// "Alisson" per il Napoli.
const LIKELY_STARTERS = {
  "carnesecchi|atalanta": true,
  "zappacosta|atalanta": true,
  "scalvini|atalanta": true,
  "hien|atalanta": true,
  "ahanor|atalanta": true,
  "ederson d.s.|atalanta": true,
  "gaetano|atalanta": true,
  "pasalic|atalanta": true,
  "de ketelaere|atalanta": true,
  "scamacca|atalanta": true,
  "raspadori|atalanta": true,
  "skorupski|bologna": true,
  "zortea|bologna": true,
  "heggem|bologna": true,
  "lucumì|bologna": true,
  "miranda j.|bologna": true,
  "ferguson|bologna": true,
  "moro n.|bologna": true,
  "bernardeschi|bologna": true,
  "orsolini|bologna": true,
  "dovbyk|bologna": true,
  "rowe|bologna": true,
  "caprile|cagliari": true,
  "zè pedro|cagliari": true,
  "mina|cagliari": true,
  "rodriguez ju.|cagliari": true,
  "zappa|cagliari": true,
  "adopo|cagliari": true,
  "deiola|cagliari": true,
  "fazzini|cagliari": true,
  "obert|cagliari": true,
  "borrelli|cagliari": true,
  "butez|como": true,
  "couto|como": true,
  "ramon|como": true,
  "kempf|como": true,
  "kaiki|como": true,
  "da cunha|como": true,
  "perrone|como": true,
  "diao|como": true,
  "baturina|como": true,
  "douvikas|como": true,
  "paz n.|como": true,
  "de gea|fiorentina": true,
  "dodò|fiorentina": true,
  "dragusin|fiorentina": true,
  "viery|fiorentina": true,
  "jimenez a.|fiorentina": true,
  "oulai|fiorentina": true,
  "fagioli|fiorentina": true,
  "ndour|fiorentina": true,
  "atta|fiorentina": true,
  "kean|fiorentina": true,
  "mastantuono|fiorentina": true,
  "palmisani|frosinone": true,
  "oyono a.|frosinone": true,
  "monterisi|frosinone": true,
  "cittadini|frosinone": true,
  "bracaglia|frosinone": true,
  "calò|frosinone": true,
  "hasa|frosinone": true,
  "koutsoupias|frosinone": true,
  "ghedjemis|frosinone": true,
  "raimondo|frosinone": true,
  "kvernadze|frosinone": true,
  "bijlow|genoa": true,
  "marcandalli|genoa": true,
  "ostigard|genoa": true,
  "vasquez|genoa": true,
  "norton-cuffy|genoa": true,
  "frendrup|genoa": true,
  "mitaj|genoa": true,
  "baldanzi|genoa": true,
  "vitinha o.|genoa": true,
  "colombo|genoa": true,
  "sow|genoa": true,
  "martinez jo.|inter": true,
  "bisseck|inter": true,
  "akanji|inter": true,
  "bastoni|inter": true,
  "diouf|inter": true,
  "barella|inter": true,
  "calhanoglu|inter": true,
  "sucic p.|inter": true,
  "dimarco|inter": true,
  "thuram|inter": true,
  "martinez l.|inter": true,
  "di gregorio|juventus": true,
  "kalulu|juventus": true,
  "bremer|juventus": true,
  "kelly l.|juventus": true,
  "cambiaso|juventus": true,
  "locatelli|juventus": true,
  "thuram k.|juventus": true,
  "conceicao|juventus": true,
  "mckennie|juventus": true,
  "yildiz|juventus": true,
  "kolo muani|juventus": true,
  "mandas|lazio": true,
  "marusic|lazio": true,
  "doekhi|lazio": true,
  "romagnoli|lazio": true,
  "tavares n.|lazio": true,
  "dele-bashiru|lazio": true,
  "rovella|lazio": true,
  "taylor k.|lazio": true,
  "isaksen|lazio": true,
  "noslin|lazio": true,
  "zaccagni|lazio": true,
  "falcone|lecce": true,
  "veiga d.|lecce": true,
  "gaspar k.|lecce": true,
  "tiago gabriel|lecce": true,
  "gallo|lecce": true,
  "ngom|lecce": true,
  "coulibaly l.|lecce": true,
  "pierotti|lecce": true,
  "gandelman|lecce": true,
  "geubbels|lecce": true,
  "n'dri|lecce": true,
  "maignan|milan": true,
  "gila|milan": true,
  "gabbia|milan": true,
  "pavlovic|milan": true,
  "saelemaekers|milan": true,
  "modric|milan": true,
  "rabiot|milan": true,
  "bartesaghi|milan": true,
  "nkunku|milan": true,
  "pulisic|milan": true,
  "ramos g.|milan": true,
  "thiam|monza": true,
  "birindelli|monza": true,
  "delli carri|monza": true,
  "carboni a.|monza": true,
  "bakoune|monza": true,
  "pessina|monza": true,
  "akinsanmiro|monza": true,
  "mangas|monza": true,
  "colpani|monza": true,
  "mota|monza": true,
  "cutrone|monza": true,
  "meret|napoli": true,
  "di lorenzo|napoli": true,
  "rrahmani|napoli": true,
  "buongiorno|napoli": true,
  "spinazzola|napoli": true,
  "de bruyne|napoli": true,
  "lobotka|napoli": true,
  "mctominay|napoli": true,
  "politano|napoli": true,
  "hojlund|napoli": true,
  "suzuki|parma": true,
  "circati|parma": true,
  "troilo|parma": true,
  "ndiaye|parma": true,
  "delprato|parma": true,
  "bernabè|parma": true,
  "keita m.|parma": true,
  "nicolussi caviglia|parma": true,
  "valeri|parma": true,
  "pellegrino m.|parma": true,
  "tourè e.|parma": true,
  "svilar|roma": true,
  "hermoso|roma": true,
  "mancini|roma": true,
  "rensch|roma": true,
  "cristante|roma": true,
  "konè m.|roma": true,
  "wesley|roma": true,
  "soulè|roma": true,
  "dybala|roma": true,
  "malen|roma": true,
  "n'dicka|roma": true,
  "muric|sassuolo": true,
  "walukiewicz|sassuolo": true,
  "candè|sassuolo": true,
  "idzes|sassuolo": true,
  "doig|sassuolo": true,
  "thorstvedt|sassuolo": true,
  "matic|sassuolo": true,
  "adzic|sassuolo": true,
  "berardi|sassuolo": true,
  "pinamonti|sassuolo": true,
  "laurientè|sassuolo": true,
  "paleari|torino": true,
  "comuzzo|torino": true,
  "comert|torino": true,
  "coco|torino": true,
  "pedersen|torino": true,
  "casadei|torino": true,
  "ilkhan|torino": true,
  "vlasic|torino": true,
  "cacciamani|torino": true,
  "simeone|torino": true,
  "zapata d.|torino": true,
  "okoye|udinese": true,
  "kristensen t.|udinese": true,
  "kabasele|udinese": true,
  "solet|udinese": true,
  "vojvoda|udinese": true,
  "ekkelenkamp|udinese": true,
  "karlstrom|udinese": true,
  "unai gomez|udinese": true,
  "kamara h.|udinese": true,
  "zaniolo|udinese": true,
  "davis k.|udinese": true,
  "stankovic f.|venezia": true,
  "bella-kotchap|venezia": true,
  "schingtienne|venezia": true,
  "moreno m.|venezia": true,
  "correia t.|venezia": true,
  "basic|venezia": true,
  "busio|venezia": true,
  "sohm|venezia": true,
  "haps|venezia": true,
  "adams a.|venezia": true,
  "yeboah j.|venezia": true
};
